/**:
  ros__parameters:
    camera_info_url: "package://hik_camera_ros2_driver/config/camera_info.yaml"
    pixel_format: "BayerRG8"
    use_sensor_data_qos: true

    camera_name: "cam1"
    frame_id: "cam1_optical_frame"
    camera_topic: "/cam1/image_raw"
    camera_serial: "00J38611359"

    acquisition_frame_rate: 120.0
    exposure_time: 16000
    gain: 16.0

    # cam1 is ROS2-only in this template
    enable_ros_publish: true
